graph = TinkerGraph.open()
g = graph.traversal()
p_A = g.addV('package').property('fqname', 'A').next()
p_B = g.addV('package').property('fqname', 'B').next()
p_C = g.addV('package').property('fqname', 'C').next()
p_D = g.addV('package').property('fqname', 'D').next()
p_E = g.addV('package').property('fqname', 'E').next()
v_A1 = g.addV('version').property('fqname', 'A@1.0.0').property('version', '1.0.0').next()
v_A2 = g.addV('version').property('fqname', 'A@2.0.0').property('version', '2.0.0').next()
v_B2 = g.addV('version').property('fqname', 'B@2.0.0').property('version', '2.0.0').next()
v_C2 = g.addV('version').property('fqname', 'C@2.0.0').property('version', '2.0.0').next()
v_C3 = g.addV('version').property('fqname', 'C@3.0.0').property('version', '3.0.0').next()
v_D3 = g.addV('version').property('fqname', 'D@3.0.0').property('version', '3.0.0').next()
v_E4 = g.addV('version').property('fqname', 'E@4.0.0').property('version', '4.0.0').next()
g.addE('has').from(p_A).to(v_A1).next()
g.addE('has').from(p_A).to(v_A2).next()
g.addE('has').from(p_B).to(v_B2).next()
g.addE('has').from(p_C).to(v_C2).next()
g.addE('has').from(p_C).to(v_C3).next()
g.addE('has').from(p_D).to(v_D3).next()
g.addE('has').from(p_E).to(v_E4).next()
g.addE('depends').from(v_A1).to(v_B2).next()
g.addE('depends').from(v_A1).to(v_C2).next()
g.addE('depends').from(v_A2).to(v_C3).next()
g.addE('depends').from(v_C2).to(v_D3).next()
g.addE('depends').from(v_C3).to(v_E4).next()
g.V().has('package', 'fqname', 'A').out('has').has('version', '1.0.0').until(__.not(out('depends').simplePath())).repeat(out('depends').simplePath()).tree().by('fqname')
